In [2]:
import numpy as np
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [5]:
b=np.ones(4) +1

a-b

array([-1.,  0.,  1.,  2.])

In [6]:
a*b

array([2., 4., 6., 8.])

In [7]:
c=np.diag([1,2,3,4])
print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [8]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [9]:
a>b

array([False, False,  True, False])

In [10]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,b)

False

In [11]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,c)

True

In [12]:
a=np.array([1,1,0,0], dtype=bool)
a=np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True,  True])

In [13]:
a=np.array([1,1,0,0], dtype=bool)
a=np.array([1,0,1,0], dtype=bool)

np.logical_and(a,b)

array([ True, False,  True, False])

In [15]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [17]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [19]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [21]:
x.sum(axis=0)

array([3, 3])

In [22]:
x.sum(axis=1)

array([2, 4])

In [23]:
x=np.array([1,3,2])
x.min()

1

In [24]:
x.max()

3

In [25]:
x.argmin()

0

In [26]:
x.argmax()

1

In [27]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [28]:
np.all(a==a)

True

In [29]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [30]:
np.median(y,axis=-1)

array([2., 5.])

In [35]:
 data=np.loadtxt('populations.txt')


In [36]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [37]:
year, hares, lynxes,carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [38]:
populations=data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [39]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [40]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [42]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [43]:
a=a.T

In [44]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [46]:
a1=np.tile(np.arange(0,40,10),(3,2))
print(a1)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [48]:
b=np.array([0,1,2])

In [50]:
b

array([0, 1, 2])

In [51]:
a

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [52]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

a=a.T
a

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [53]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [56]:
a=np.array([0,10,20,30])
a

array([ 0, 10, 20, 30])

In [55]:
b=np.array([0,1,2])

In [57]:
a=a[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [58]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [59]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [60]:
print(a.shape)

(2, 3)


In [62]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [63]:
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
b[0,0]=100
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [65]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [66]:
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50

a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [68]:
z=np.array([1,2,3])
z

array([1, 2, 3])

In [69]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [70]:
a=np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [71]:
a[0,2,1]

5

In [72]:
a=np.arange(4)
a.resize(8)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [74]:
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [75]:
a=np.array([4,3,1,2])
j=np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [76]:
a[j]

array([1, 2, 3, 4])