In [2]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
L=range(1000)
%timeit [ i**2 for i in L]

768 µs ± 36.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

3.07 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [9]:
len(a)

4

In [12]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b.ndim


2

In [14]:
b.shape

(2, 3)

In [15]:
len(b)

2

In [23]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
c.ndim

3

In [25]:
c.shape


(2, 2, 2)

In [27]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [29]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
np.diag(a)

array([1, 2, 3, 4])

In [36]:
a= np.random.rand(4) 
a

array([0.71229053, 0.66569218, 0.15981792, 0.02773601])

In [38]:
a=np.random.randn(4)
a

array([-1.58099013, -1.11026448, -1.16089996,  0.38379546])

In [39]:
a=np.arange(10)
a.dtype

dtype('int32')

In [41]:
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
d=np.array([1+2j,2+4j])
d.dtype

dtype('complex128')

In [46]:
b=np.array([True,True,False])
b.dtype

dtype('bool')

In [47]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[1:8:2]

array([1, 3, 5, 7])

In [50]:
a[5:] =10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [51]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [52]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [53]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [55]:
np.shares_memory(a,b)

True

In [56]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [57]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [58]:
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [59]:
np.shares_memory(a,c)

False

In [60]:
a=np.random.randint(0,20,15)
a

array([ 1,  5, 10,  5, 19, 11, 18, 12, 17, 12, 11, 13,  3, 12,  9])

In [61]:
mask = (a%2==0)

In [62]:
extract_from_a = a[mask]
extract_from_a

array([10, 18, 12, 12, 12])

In [63]:
a[mask]=-1
a

array([ 1,  5, -1,  5, 19, 11, -1, -1, 17, -1, 11, 13,  3, -1,  9])

In [65]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [68]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])