In [1]:
import pandas as pd
df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [2]:
print(df['event'])

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object


In [3]:
print(df[['event']])

   event
0   Rain
1  Sunny
2   Snow
3   Snow
4   Rain
5  Sunny


In [6]:
print(type(df['event']))
print(type(df[['event']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [7]:
print(df[['temperature','event']])

   temperature  event
0           32   Rain
1           35  Sunny
2           28   Snow
3           24   Snow
4           32   Rain
5           31  Sunny


In [8]:
print(type(df[['temperature','event']]))

<class 'pandas.core.frame.DataFrame'>


In [9]:
df.loc[:,['temperature','event']]

temperature  event
0           32   Rain
1           35  Sunny
2           28   Snow
3           24   Snow
4           32   Rain
5           31  Sunny

In [14]:
df['event']=='Rain'

0     True
1    False
2    False
3    False
4     True
5    False
Name: event, dtype: bool

In [13]:
print(df[df['event']=='Rain'])

          day  temperature  windspeed event
0  01-01-2017           32          6  Rain
4  01-05-2017           32          4  Rain


In [10]:
df[df['event']=='Rain'][['temperature','windspeed']]

temperature  windspeed
0           32          6
4           32          4

In [11]:
df1 = df[df['event']=='Rain']
df1[['temperature','windspeed']]

temperature  windspeed
0           32          6
4           32          4

In [15]:
df[['temperature','windspeed']][df['event']=='Rain']

temperature  windspeed
0           32          6
4           32          4

In [16]:
df['temperature'][df.event == 'Rain']

0    32
4    32
Name: temperature, dtype: int64

In [17]:
df[['temperature','windspeed']][df.event == 'Rain']

temperature  windspeed
0           32          6
4           32          4

In [18]:
df_test = pd.DataFrame([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(df_test)

    0   1   2   3
0  11  12  13  14
1  21  22  23  24
2  31  32  33  34


In [19]:
df_test = pd.DataFrame([[11,12,13,14],[21,22,23,24],[31,32,33,3,400]])
print(df_test)

    0   1   2   3      4
0  11  12  13  14    NaN
1  21  22  23  24    NaN
2  31  32  33   3  400.0


In [20]:
df_test = pd.DataFrame([[11,12,13,14],[21,22,23,24],[31,32,33,'3,400']])
print(df_test)

    0   1   2      3
0  11  12  13     14
1  21  22  23     24
2  31  32  33  3,400


In [21]:
print(df_test.iloc[2,3])

3,400


In [22]:
print(type(df_test.iloc[2,3]))

<class 'str'>


In [24]:
df['temperature'].max()

35

In [30]:
df[df['temperature'] == df['temperature'].max()]

day  temperature  windspeed  event
1  01-02-2017           35          7  Sunny

In [32]:
df['windspeed'][df['temperature']==df['temperature'].max()]

1    7
Name: windspeed, dtype: int64

In [33]:
df[2:5]

day  temperature  windspeed event
2  01-03-2017           28          2  Snow
3  01-04-2017           24          7  Snow
4  01-05-2017           32          4  Rain

In [36]:
df.iloc[2:5,0:2]

day  temperature
2  01-03-2017           28
3  01-04-2017           24
4  01-05-2017           32

## PROBLEMS




### Combine 2 series to form a dataframe

In [6]:
import numpy as np
import pandas as pd
data1 = np.array(['a','b','c','d','e'])
data2 = np.array([1,2,3,4,5])
s1 = pd.Series(data1)
s2 = pd.Series(data2)

In [7]:
df = pd.DataFrame({'col1':s1,'col2':s2})

In [8]:
df

col1  col2
0    a     1
1    b     2
2    c     3
3    d     4
4    e     5

### From s1 remove items present in s2

In [9]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([4,5,6,7,8])

In [10]:
print(s1.isin(s2))

0    False
1    False
2    False
3     True
4     True
dtype: bool


In [11]:
print(s1[-s1.isin(s2)])

0    1
1    2
2    3
dtype: int64


### Extract the valid emails from the series emails

In [13]:
emails = pd.Series(['buying books at amazon.com','manasar259@gmail.com'])
pattern = '[A-Za-z0-9._&+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
import re
print(emails.str.findall(pattern,flags = re.IGNORECASE))

0                        []
1    [manasar259@gmail.com]
dtype: object


### Get position of peaks in a series

In [14]:
ser = pd.Series([2,10,5,4,9,10,2,7,3])

print(np.diff(ser))

[ 8 -5 -1  5  1 -8  5 -4]


In [15]:
np.sign(np.diff(ser))

array([ 1, -1, -1,  1,  1, -1,  1, -1], dtype=int64)

In [19]:
dd = np.diff(np.sign(np.diff(ser)))
print(dd)

[-2  0  2  0 -2  2 -2]


In [22]:
peak_locs = np.where(dd == -2)[0]

TypeError: can only concatenate tuple (not "int") to tuple